### ISSUE TITLE
Thank you and a few doubts

### ISSUE THREAD

**Issue by sayakpaul** [wangz10/contrastive_loss#1]
Hi @wangz10,

Thank you for putting together this repository and also [the blog post](https://towardsdatascience.com/contrastive-loss-for-supervised-classification-224ae35692e7). After going through the code, I had the following doubts. If you could help me clarify I would really appreciate it:
- While training the baseline classifier, did you train the network without normalizing the features? In typical image classification models, the normalization step is not often seen I would say. 
- Did you normalize the features for both the encoder and the projector? 
- If you could provide some high-level explanation of the `max_margin_contrastive_loss` function, it would be very helpful.

Thank you and looking forward to hearing from you.

**Comment by wangz10** [comment]
Hi @sayakpaul ,

- Input images are normalized to [0,1] by dividing 255. 
- Yes, the outputs from encoder and the projector are both normalized to have unit norm.
- `max_margin_contrastive_loss` is a wrapper for `tfa.losses.contrastive_loss`. I just computed the pairwise Euclidean/cosine distance, retrieve the upper triangle, then feed it into `tfa.losses.contrastive_loss`.

**Comment by sayakpaul** [comment]
Thanks for providing the additional details @wangz10. 

I am referring to [this implementation of the baseline architecture](https://github.com/wangz10/contrastive_loss/blob/master/model.py#L94) where you used wherein it seems like you have also normalized the features within the network which is where my doubt. 

Regarding `max_margin_contrastive_loss`, could you provide some details regarding your approach towards computing the contrastive pairs?
